# Generated by Django 4.0.1 on 2022-03-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetup_and_hangout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meetup_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('currently_on', models.BooleanField(default=False)),
                ('regular', models.BooleanField(default=False)),
                ('meetup_time_date', models.TimeField()),
                ('poster', models.ImageField(null=True, upload_to='Events/')),
                ('organizor', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_cell', models.CharField(max_length=20)),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.building')),
            ],
        ),
    ]
