# Generated by Django 4.0.1 on 2022-01-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_building_id_alter_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('evenTime', models.TimeField()),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.building')),
            ],
        ),
        migrations.CreateModel(
            name='buildingPic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.building')),
            ],
        ),
    ]
