# Generated by Django 4.0.1 on 2022-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_event_buildingpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_on',
            field=models.BooleanField(default=False),
        ),
    ]
