# Generated by Django 4.0.1 on 2022-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_building_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='alias',
            field=models.CharField(max_length=15),
        ),
    ]
