# Generated by Django 4.0.1 on 2022-03-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_building_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
